import { STATUS_LABEL, type TranslationStatus } from "@/lib/types";

export function StatusBadge({ status }: { status: TranslationStatus }) {
  return <span className={`status-pill status-${status}`}>{STATUS_LABEL[status]}</span>;
}

export function ChangePill({ status }: { status: "new" | "changed" | "unchanged" | "removed" }) {
  if (status === "unchanged") return null;
  const label = status === "new" ? "New" : status === "changed" ? "Changed" : "Removed";
  return <span className={`change-pill change-${status}`}>{label}</span>;
}

export function AiBadge({ model }: { model?: string | null }) {
  return (
    <span
      className="ai-badge"
      title={model ? `Machine-generated by ${model} — review before approving` : "Machine-generated — review before approving"}
    >
      ✨ AI draft
    </span>
  );
}
